M48
; DRILL file {KiCad (6.0.0)} date Mon Feb 21 14:52:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-21T14:52:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0454
%
G90
G05
T1
X6.24Y-3.5336
X6.24Y-3.7612
T2
X4.9369Y-3.2677
X5.572Y-4.0577
X6.1969Y-3.2677
T0
M30
